#include "ConditionCreator.h"

#include  "Plans/test/teste2/NewPlan1450174760570.h"

#include  "Plans/UnconnectedState1441701808444.h"

#include  "Plans/MasterPlan1441701747919.h"

using namespace alicaAutogenerated;
namespace alica
{

    ConditionCreator::ConditionCreator()
    {
    }
    ConditionCreator::~ConditionCreator()
    {
    }

    shared_ptr<BasicCondition> ConditionCreator::createConditions(long conditionConfId)
    {
        switch (conditionConfId)
        {

            case 1441701794882:

                return make_shared<TransitionCondition1441701794882>();

                break;

            default:
                cerr << "ConditionCreator: Unknown condition id requested: " << conditionConfId << endl;
                throw new exception();
                break;
        }
    }
}
