#include "ConstraintCreator.h"
#include <iostream>

#include  "Plans/constraints/LocalInconsistentCardinalities1453033347284Constraints.h"

#include  "Plans/constraints/CyclePlanB1453033643893Constraints.h"

#include  "Plans/constraints/UnconnectedStateMachine1452783558494Constraints.h"

#include  "Plans/constraints/CyclePlanC1453033651069Constraints.h"

#include  "Plans/constraints/SingleUnconnectedState1452783421979Constraints.h"

#include  "Plans/constraints/CyclePlanA1453033636578Constraints.h"

#include  "Plans/constraints/TaskTwicePlan1453033761283Constraints.h"

#include  "Plans/constraints/HierarchicalInconsistentCardinalities1453033407259Constraints.h"

#include  "Plans/constraints/Min3AgentPlan1453033506291Constraints.h"

using namespace std;
using namespace alicaAutogenerated;

namespace alica
{

    ConstraintCreator::ConstraintCreator()
    {
    }

    ConstraintCreator::~ConstraintCreator()
    {
    }

    shared_ptr<BasicConstraint> ConstraintCreator::createConstraint(long constraintConfId)
    {
        switch (constraintConfId)
        {

            default:
                cerr << "ConstraintCreator: Unknown constraint requested: " << constraintConfId << endl;
                throw new exception();
                break;
        }
    }

}
