#include <iostream>
#include "UtilityFunctionCreator.h"

#include  "Plans/UnconnectedState1441701808444.h"

#include  "Plans/MasterPlan1441701747919.h"

using namespace std;
using namespace alicaAutogenerated;
namespace alica
{

    UtilityFunctionCreator::~UtilityFunctionCreator()
    {
    }

    UtilityFunctionCreator::UtilityFunctionCreator()
    {
    }

    shared_ptr<BasicUtilityFunction> UtilityFunctionCreator::createUtility(long utilityfunctionConfId)
    {
        switch (utilityfunctionConfId)
        {

            case 1450174760570:
                return make_shared<UtilityFunction1450174760570>();
                break;

            case 1441701808444:
                return make_shared<UtilityFunction1441701808444>();
                break;

            case 1441701747919:
                return make_shared<UtilityFunction1441701747919>();
                break;

            default:
                cerr << "UtilityFunctionCreator: Unknown utility requested: " << utilityfunctionConfId << endl;
                throw new exception();
                break;
        }
    }

}
