#include <iostream>
#include "UtilityFunctionCreator.h"

#include  "Plans/LocalInconsistentCardinalities1453033347284.h"

#include  "Plans/CyclePlanB1453033643893.h"

#include  "Plans/UnconnectedStateMachine1452783558494.h"

#include  "Plans/CyclePlanC1453033651069.h"

#include  "Plans/SingleUnconnectedState1452783421979.h"

#include  "Plans/CyclePlanA1453033636578.h"

#include  "Plans/TaskTwicePlan1453033761283.h"

#include  "Plans/HierarchicalInconsistentCardinalities1453033407259.h"

#include  "Plans/Min3AgentPlan1453033506291.h"

using namespace std;
using namespace alicaAutogenerated;
namespace alica
{

    UtilityFunctionCreator::~UtilityFunctionCreator()
    {
    }

    UtilityFunctionCreator::UtilityFunctionCreator()
    {
    }

    shared_ptr<BasicUtilityFunction> UtilityFunctionCreator::createUtility(long utilityfunctionConfId)
    {
        switch (utilityfunctionConfId)
        {

            case 1453033347284:
                return make_shared<UtilityFunction1453033347284>();
                break;

            case 1453033643893:
                return make_shared<UtilityFunction1453033643893>();
                break;

            case 1452783558494:
                return make_shared<UtilityFunction1452783558494>();
                break;

            case 1453033651069:
                return make_shared<UtilityFunction1453033651069>();
                break;

            case 1452783421979:
                return make_shared<UtilityFunction1452783421979>();
                break;

            case 1453033636578:
                return make_shared<UtilityFunction1453033636578>();
                break;

            case 1453033761283:
                return make_shared<UtilityFunction1453033761283>();
                break;

            case 1453033407259:
                return make_shared<UtilityFunction1453033407259>();
                break;

            case 1453033506291:
                return make_shared<UtilityFunction1453033506291>();
                break;

            default:
                cerr << "UtilityFunctionCreator: Unknown utility requested: " << utilityfunctionConfId << endl;
                throw new exception();
                break;
        }
    }

}
