#ifndef CyclePlanBCONSTRAINT_H_
#define CyclePlanB_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* CyclePlanBCONSTRAINT_H_ */
