#ifndef CyclePlanCCONSTRAINT_H_
#define CyclePlanC_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* CyclePlanCCONSTRAINT_H_ */
