#ifndef HierarchicalInconsistentCardinalitiesCONSTRAINT_H_
#define HierarchicalInconsistentCardinalities_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* HierarchicalInconsistentCardinalitiesCONSTRAINT_H_ */
