#ifndef InRelationPlanCONSTRAINT_H_
#define InRelationPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
} // namespace alica

namespace alicaAutogenerated
{

} // namespace alicaAutogenerated

#endif /* InRelationPlanCONSTRAINT_H_ */
