#ifndef InRelationPlanCONSTRAINT_H_
#define InRelationPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* InRelationPlanCONSTRAINT_H_ */
