#ifndef LowerPlanInPlantypeCONSTRAINT_H_
#define LowerPlanInPlantype_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* LowerPlanInPlantypeCONSTRAINT_H_ */
