#ifndef Min3AgentPlanCONSTRAINT_H_
#define Min3AgentPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* Min3AgentPlanCONSTRAINT_H_ */
