#ifndef Min3AgentPlanCONSTRAINT_H_
#define Min3AgentPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
} // namespace alica

namespace alicaAutogenerated
{

} // namespace alicaAutogenerated

#endif /* Min3AgentPlanCONSTRAINT_H_ */
