#ifndef NonLocalInRelationCONSTRAINT_H_
#define NonLocalInRelation_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* NonLocalInRelationCONSTRAINT_H_ */
