#ifndef ReferencedPlanCONSTRAINT_H_
#define ReferencedPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
} // namespace alica

namespace alicaAutogenerated
{

} // namespace alicaAutogenerated

#endif /* ReferencedPlanCONSTRAINT_H_ */
