#ifndef ReusePlanFromPlantypeWithoutCycleCONSTRAINT_H_
#define ReusePlanFromPlantypeWithoutCycle_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* ReusePlanFromPlantypeWithoutCycleCONSTRAINT_H_ */
