#ifndef ReusePlanFromPlantypeWithoutCycleCONSTRAINT_H_
#define ReusePlanFromPlantypeWithoutCycle_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
} // namespace alica

namespace alicaAutogenerated
{

} // namespace alicaAutogenerated

#endif /* ReusePlanFromPlantypeWithoutCycleCONSTRAINT_H_ */
