#ifndef SingleUnconnectedStateCONSTRAINT_H_
#define SingleUnconnectedState_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* SingleUnconnectedStateCONSTRAINT_H_ */
