#ifndef TaskTwicePlanCONSTRAINT_H_
#define TaskTwicePlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
} // namespace alica

namespace alicaAutogenerated
{

} // namespace alicaAutogenerated

#endif /* TaskTwicePlanCONSTRAINT_H_ */
