#ifndef UnconnectedStateMachineCONSTRAINT_H_
#define UnconnectedStateMachine_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
} // namespace alica

namespace alicaAutogenerated
{

} // namespace alicaAutogenerated

#endif /* UnconnectedStateMachineCONSTRAINT_H_ */
