#ifndef UpperPlanInPlantypeCONSTRAINT_H_
#define UpperPlanInPlantype_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* UpperPlanInPlantypeCONSTRAINT_H_ */
