#include "Plans/Assistance/CarryBook1462889426092.h"
using namespace alica;
/*PROTECTED REGION ID(eph1462889426092) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:CarryBook

// Check of PreCondition - (Name): NewPreCondition, (ConditionString): agent(A), in(A,p1462889426092, tsk1225112227903, S),  carries(A, harryPotter1). ,
// (Comment) :

/*
 * Available Vars:
 */
bool PreCondition1463404630976::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1463404630976) ENABLED START*/
    //--> "PreCondition:1463404630976  not implemented";
    return true;
    /*PROTECTED REGION END*/
}

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1462889438751

 */
shared_ptr<UtilityFunction> UtilityFunction1462889426092::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1462889426092) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: CarryBook in Plan: CarryBook

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment :
 *
 * Plans in State:
 *   - Plan - (Name): CarryDefault, (PlanID): 1463077955666
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1462889438751)
 *
 * States:
 *   - CarryBook (1462889438750)
 *   - DeliverBook (1463404627637)
 *
 * Vars:
 */
bool TransitionCondition1463404654846::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1463404653224) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}

// State: DeliverBook in Plan: CarryBook

} // namespace alicaAutogenerated
