#include "Plans/Assistance/InnerPlan1464027589619.h"
using namespace alica;
/*PROTECTED REGION ID(eph1464027589619) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:InnerPlan

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1464027605608

     */
    shared_ptr<UtilityFunction> UtilityFunction1464027589619::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1464027589619) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: State in Plan: InnerPlan

}
