#include "Plans/Assistance/SecondInnerPlan1464027620934.h"
using namespace alica;
/*PROTECTED REGION ID(eph1464027620934) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:SecondInnerPlan

    //Check of PreCondition - (Name): NewPreCondition, (ConditionString): agent(A), in(A,p1464027620934, tsk1225112227903, S). , (Comment) :  

    /*
     * Available Vars:
     */
    bool PreCondition1464080078059::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1464080078059) ENABLED START*/
        //--> "PreCondition:1464080078059  not implemented";
        return true;
        /*PROTECTED REGION END*/
    }

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1464027640745

     */
    shared_ptr<UtilityFunction> UtilityFunction1464027620934::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1464027620934) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: NewState in Plan: SecondInnerPlan

}
