#include "Plans/Assistance/SecondInnerPlan1464027620934.h"
using namespace alica;
/*PROTECTED REGION ID(eph1464027620934) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:SecondInnerPlan

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1464027640745

     */
    shared_ptr<UtilityFunction> UtilityFunction1464027620934::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1464027620934) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: NewState in Plan: SecondInnerPlan

}
