#ifndef CyclePlanA_H_
#define CyclePlanA_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
#include "engine/UtilityFunction.h"
/*PROTECTED REGION ID(incl1453033636578) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1453033636578) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1453033636578 : public BasicUtilityFunction
{
    shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

} // namespace alicaAutogenerated

#endif
