#ifndef IndirectReusePlanInPlantype_H_
#define IndirectReusePlanInPlantype_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
#include "engine/UtilityFunction.h"
/*PROTECTED REGION ID(incl1462793790517) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1462793790517) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1462793790517 : public BasicUtilityFunction
{
    shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

} // namespace alicaAutogenerated

#endif
