#ifndef ReusePlanFromPlantypeWithoutCycle_H_
#define ReusePlanFromPlantypeWithoutCycle_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
#include "engine/UtilityFunction.h"
/*PROTECTED REGION ID(incl1464355916688) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1464355916688) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1464355916688 : public BasicUtilityFunction
{
    shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

} // namespace alicaAutogenerated

#endif
