#include "Plans/BrokenCardPlan1462879159773.h"
using namespace alica;
/*PROTECTED REGION ID(eph1462879159773) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:BrokenCardPlan

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1462879191637

     */
    shared_ptr<UtilityFunction> UtilityFunction1462879159773::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1462879159773) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: BrokenPlanState in Plan: BrokenCardPlan

}
