#include "Plans/CorrectCardPlan1462879199379.h"
using namespace alica;
/*PROTECTED REGION ID(eph1462879199379) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:CorrectCardPlan

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1462879220967

 */
shared_ptr<UtilityFunction> UtilityFunction1462879199379::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1462879199379) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: CorrectPlanState in Plan: CorrectCardPlan

} // namespace alicaAutogenerated
