#include "Plans/CyclePlanB1453033643893.h"
using namespace alica;
/*PROTECTED REGION ID(eph1453033643893) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:CyclePlanB

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1453033643895

     */
    shared_ptr<UtilityFunction> UtilityFunction1453033643893::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1453033643893) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: NewState in Plan: CyclePlanB

}
