#include "Plans/CyclePlanA1453033636578.h"
using namespace alica;
/*PROTECTED REGION ID(eph1453033636578) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:CyclePlanA

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1453033636581

     */
    shared_ptr<UtilityFunction> UtilityFunction1453033636578::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1453033636578) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: NewState in Plan: CyclePlanA

}
