#include "Plans/CyclePlanC1453033651069.h"
using namespace alica;
/*PROTECTED REGION ID(eph1453033651069) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:CyclePlanC

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1453033651071

 */
shared_ptr<UtilityFunction> UtilityFunction1453033651069::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1453033651069) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: NewState in Plan: CyclePlanC

} // namespace alicaAutogenerated
