#include "Plans/EmptyPlan1455034580394.h"
using namespace alica;
/*PROTECTED REGION ID(eph1455034580394) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:EmptyPlan

    /* generated comment
     
     */
    shared_ptr<UtilityFunction> UtilityFunction1455034580394::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1455034580394) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

}
