#include "Plans/HierarchicalInconsistentCardinalities1453033407259.h"
using namespace alica;
/*PROTECTED REGION ID(eph1453033407259) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:HierarchicalInconsistentCardinalities

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1453033407261

 */
shared_ptr<UtilityFunction> UtilityFunction1453033407259::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1453033407259) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: Max2AgentState in Plan: HierarchicalInconsistentCardinalities

} // namespace alicaAutogenerated
