#include "Plans/InconsistentCardinalities1462886292442.h"
using namespace alica;
/*PROTECTED REGION ID(eph1462886292442) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:InconsistentCardinalities

    /* generated comment
     
     Task: Attack  -> EntryPoint-ID: 1462886292444

     Task: AttackSupport  -> EntryPoint-ID: 1462886310757

     */
    shared_ptr<UtilityFunction> UtilityFunction1462886292442::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1462886292442) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: NewState in Plan: InconsistentCardinalities

//State: NewState in Plan: InconsistentCardinalities

}
