#include "Plans/InconsistenCardinalities1462879046488.h"
using namespace alica;
/*PROTECTED REGION ID(eph1462879046488) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:InconsistenCardinalities

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1462879046490

 */
shared_ptr<UtilityFunction> UtilityFunction1462879046488::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1462879046488) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: PlanState in Plan: InconsistenCardinalities

} // namespace alicaAutogenerated
