#include "Plans/IndirectReusePlanInPlantype1462793790517.h"
using namespace alica;
/*PROTECTED REGION ID(eph1462793790517) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:IndirectReusePlanInPlantype

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1462793790519

     */
    shared_ptr<UtilityFunction> UtilityFunction1462793790517::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1462793790517) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: PlantypeState in Plan: IndirectReusePlanInPlantype

}
