#include "Plans/InRelationPlan1456731505906.h"
using namespace alica;
/*PROTECTED REGION ID(eph1456731505906) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:InRelationPlan

    //Check of PreCondition - (Name): InRelationPreCondition, (ConditionString): NumAgents = #count{A : agent(A), inCond(cond1456731822708, in(A,p1456731591075, tsk1225112227903, S)), State(S) }, NumAgents > 1. , (Comment) :  

    /*
     * Available Vars:
     */
    bool PreCondition1456731822708::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1456731822708) ENABLED START*/
        //--> "PreCondition:1456731822708  not implemented";
        return true;
        /*PROTECTED REGION END*/
    }

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1456731537187

     */
    shared_ptr<UtilityFunction> UtilityFunction1456731505906::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1456731505906) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: NewState in Plan: InRelationPlan

}
