#include "Plans/LocalInconsistentCardinalities1453033347284.h"
using namespace alica;
/*PROTECTED REGION ID(eph1453033347284) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:LocalInconsistentCardinalities

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1453033347286

 */
shared_ptr<UtilityFunction> UtilityFunction1453033347284::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1453033347284) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: NewState in Plan: LocalInconsistentCardinalities

} // namespace alicaAutogenerated
