#include "Plans/MasterPlan1441701747919.h"
using namespace alica;
/*PROTECTED REGION ID(eph1441701747919) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:MasterPlan

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1441701747921

 */
shared_ptr<UtilityFunction> UtilityFunction1441701747919::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1441701747919) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: RootState in Plan: MasterPlan

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment :
 *
 * Plans in State:
 *   - Plan - (Name): UnconnectedState, (PlanID): 1441701808444
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1441701747921)
 *
 * States:
 *   - RootState (1441701747920)
 *   - SecondRootState (1441701781326)
 *
 * Vars:
 */
bool TransitionCondition1441701794882::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1441701794000) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}

// State: SecondRootState in Plan: MasterPlan

} // namespace alicaAutogenerated
