#include "Plans/Min3AgentPlan1453033506291.h"
using namespace alica;
/*PROTECTED REGION ID(eph1453033506291) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:Min3AgentPlan

    /* generated comment
     
     Task: Attack  -> EntryPoint-ID: 1453033506293

     Task: Defend  -> EntryPoint-ID: 1456483257411

     */
    shared_ptr<UtilityFunction> UtilityFunction1453033506291::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1453033506291) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: Min2AgentState in Plan: Min3AgentPlan

//State: Min1AgentState in Plan: Min3AgentPlan

}
