#include "Plans/NonLocalInRelation1456730912737.h"
using namespace alica;
/*PROTECTED REGION ID(eph1456730912737) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:NonLocalInRelation

    /* generated comment
     
     Task: Attack  -> EntryPoint-ID: 1456730912739

     Task: Defend  -> EntryPoint-ID: 1456731546744

     */
    shared_ptr<UtilityFunction> UtilityFunction1456730912737::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1456730912737) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: NonLocalInState in Plan: NonLocalInRelation

//State: ReferencedPlanState in Plan: NonLocalInRelation

}
