#include "Plans/ReferencedPlan1456731591075.h"
using namespace alica;
/*PROTECTED REGION ID(eph1456731591075) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:ReferencedPlan

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1456731605617

 */
shared_ptr<UtilityFunction> UtilityFunction1456731591075::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1456731591075) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: StateInReferencedPlan in Plan: ReferencedPlan

} // namespace alicaAutogenerated
