#include "Plans/ReusePlanWithoutCycle1455093185652.h"
using namespace alica;
/*PROTECTED REGION ID(eph1455093185652) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:ReusePlanWithoutCycle

/* generated comment

 Task: Attack  -> EntryPoint-ID: 1455093185654

 Task: Defend  -> EntryPoint-ID: 1455093221781

 */
shared_ptr<UtilityFunction> UtilityFunction1455093185652::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1455093185652) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: 1stTime in Plan: ReusePlanWithoutCycle

// State: 2ndTime in Plan: ReusePlanWithoutCycle

} // namespace alicaAutogenerated
