#include "Plans/ReusePlanFromPlantypeWithoutCycle1464355916688.h"
using namespace alica;
/*PROTECTED REGION ID(eph1464355916688) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:ReusePlanFromPlantypeWithoutCycle

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1464355916690

     */
    shared_ptr<UtilityFunction> UtilityFunction1464355916688::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1464355916688) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: PlantypeState in Plan: ReusePlanFromPlantypeWithoutCycle

}
