#include "Plans/SingleUnconnectedState1452783421979.h"
using namespace alica;
/*PROTECTED REGION ID(eph1452783421979) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:SingleUnconnectedState

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1452783421981

 */
shared_ptr<UtilityFunction> UtilityFunction1452783421979::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1452783421979) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: Unconnected State in Plan: SingleUnconnectedState

// State: AlibiState in Plan: SingleUnconnectedState

} // namespace alicaAutogenerated
