#include "Plans/UnconnectedState1441701808444.h"
using namespace alica;
/*PROTECTED REGION ID(eph1441701808444) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:UnconnectedState

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1441701830557

 */
shared_ptr<UtilityFunction> UtilityFunction1441701808444::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1441701808444) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: connected in Plan: UnconnectedState

// State: unconnected in Plan: UnconnectedState

} // namespace alicaAutogenerated
