#include "Plans/UnconnectedStateMachine1452783558494.h"
using namespace alica;
/*PROTECTED REGION ID(eph1452783558494) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:UnconnectedStateMachine

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1452783558496

     */
    shared_ptr<UtilityFunction> UtilityFunction1452783558494::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1452783558494) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: State1 in Plan: UnconnectedStateMachine

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1452783558496)
     *
     * States:
     *   - State1 (1452783558495)
     *   - State2 (1452783576711)
     *   - State3 (1452783579086)
     *   - State4 (1452783583119)
     *   - AlibiState (1453392283151)
     *
     * Vars:
     */
    bool TransitionCondition1452783594228::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1452783592558) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1452783558496)
     *
     * States:
     *   - State1 (1452783558495)
     *   - State2 (1452783576711)
     *   - State3 (1452783579086)
     *   - State4 (1452783583119)
     *   - AlibiState (1453392283151)
     *
     * Vars:
     */
    bool TransitionCondition1452783604156::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1452783601103) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: State2 in Plan: UnconnectedStateMachine

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1452783558496)
     *
     * States:
     *   - State1 (1452783558495)
     *   - State2 (1452783576711)
     *   - State3 (1452783579086)
     *   - State4 (1452783583119)
     *   - AlibiState (1453392283151)
     *
     * Vars:
     */
    bool TransitionCondition1452783597877::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1452783596070) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: State3 in Plan: UnconnectedStateMachine

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1452783558496)
     *
     * States:
     *   - State1 (1452783558495)
     *   - State2 (1452783576711)
     *   - State3 (1452783579086)
     *   - State4 (1452783583119)
     *   - AlibiState (1453392283151)
     *
     * Vars:
     */
    bool TransitionCondition1452783600822::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1452783597993) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1452783558496)
     *
     * States:
     *   - State1 (1452783558495)
     *   - State2 (1452783576711)
     *   - State3 (1452783579086)
     *   - State4 (1452783583119)
     *   - AlibiState (1453392283151)
     *
     * Vars:
     */
    bool TransitionCondition1452783605843::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1452783604345) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: State4 in Plan: UnconnectedStateMachine

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1452783558496)
     *
     * States:
     *   - State1 (1452783558495)
     *   - State2 (1452783576711)
     *   - State3 (1452783579086)
     *   - State4 (1452783583119)
     *   - AlibiState (1453392283151)
     *
     * Vars:
     */
    bool TransitionCondition1452783595930::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1452783594385) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

//State: AlibiState in Plan: UnconnectedStateMachine

}
