#include "Plans/UnconnectedSynchronisations1455035766972.h"
using namespace alica;
/*PROTECTED REGION ID(eph1455035766972) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:UnconnectedSynchronisations

    /* generated comment
     
     Task: Attack  -> EntryPoint-ID: 1455035766974

     Task: Defend  -> EntryPoint-ID: 1455035846736

     */
    shared_ptr<UtilityFunction> UtilityFunction1455035766972::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1455035766972) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: StateABefore in Plan: UnconnectedSynchronisations

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - Attack (1222613952469) (Entrypoint: 1455035766974)
     *   - Defend (1225115406909) (Entrypoint: 1455035846736)
     *
     * States:
     *   - StateABefore (1455035766973)
     *   - StateAAfter (1455035790843)
     *   - StateDBefore (1455035838383)
     *   - StateDAfter (1455035874846)
     *
     * Vars:
     */
    bool TransitionCondition1455035817820::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1455035816681) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: StateAAfter in Plan: UnconnectedSynchronisations

    //State: StateDBefore in Plan: UnconnectedSynchronisations

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - Attack (1222613952469) (Entrypoint: 1455035766974)
     *   - Defend (1225115406909) (Entrypoint: 1455035846736)
     *
     * States:
     *   - StateABefore (1455035766973)
     *   - StateAAfter (1455035790843)
     *   - StateDBefore (1455035838383)
     *   - StateDAfter (1455035874846)
     *
     * Vars:
     */
    bool TransitionCondition1455035907819::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1455035906949) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

//State: StateDAfter in Plan: UnconnectedSynchronisations

}
