#include "Plans/UpperPlanInPlantype1462793904808.h"
using namespace alica;
/*PROTECTED REGION ID(eph1462793904808) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:UpperPlanInPlantype

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1462793904810

 */
shared_ptr<UtilityFunction> UtilityFunction1462793904808::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1462793904808) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: UpperState in Plan: UpperPlanInPlantype

} // namespace alicaAutogenerated
