#include "Plans/Assistance/constraints/CarryBook1462889426092Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1462889426092) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:CarryBook

/*		
 * Tasks: 
 * - EP:1462889438751 : DefaultTask (1225112227903)
 *
 * States:
 * - CarryBook (1462889438750)
 * - DeliverBook (1463404627637)
 *
 * Vars:				
 * - BookVarPlan (1468416183422) 
 */

// State: CarryBook

// State: CarryBook

// State: DeliverBook

// State: DeliverBook

}
