#include "Plans/Assistance/constraints/CarryBookMaster1462889118325Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1462889118325) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:CarryBookMaster

/*		
 * Tasks: 
 * - EP:1462889118327 : Attack (1222613952469)
 * - EP:1462889160670 : Defend (1225115406909)
 * - EP:1464027518192 : DefaultTask (1225112227903)
 *
 * States:
 * - CarryBookState1 (1462889118326)
 * - CarryBookState2 (1462889170425)
 * - TestState (1464027526248)
 *
 * Vars:
 */

// State: CarryBookState1

// State: CarryBookState1

// State: CarryBookState2

// State: CarryBookState2

// State: TestState

// State: TestState

}
