#include "Plans/Assistance/constraints/InnerPlan1464027589619Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1464027589619) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:InnerPlan

/*
 * Tasks:
 * - EP:1464027605608 : DefaultTask (1225112227903)
 *
 * States:
 * - State (1464027605607)
 *
 * Vars:
 */

// State: State

// State: State

} // namespace alicaAutogenerated
