#include "Plans/Assistance/constraints/SecondInnerPlan1464027620934Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1464027620934) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:SecondInnerPlan

/*
 * Tasks:
 * - EP:1464027640745 : DefaultTask (1225112227903)
 *
 * States:
 * - NewState (1464027640744)
 *
 * Vars:
 */

// State: NewState

// State: NewState

} // namespace alicaAutogenerated
