#include "Plans/Assistance/constraints/ThirdInnerPlan1464091819666Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1464091819666) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:ThirdInnerPlan

/*
 * Tasks:
 * - EP:1464091833200 : DefaultTask (1225112227903)
 *
 * States:
 * - NewState (1464091833199)
 *
 * Vars:
 */

// State: NewState

// State: NewState

} // namespace alicaAutogenerated
