#ifndef CarryBookCONSTRAINT_H_
#define CarryBook_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* CarryBookCONSTRAINT_H_ */
