#ifndef InnerPlanCONSTRAINT_H_
#define InnerPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* InnerPlanCONSTRAINT_H_ */
