#ifndef SecondInnerPlanCONSTRAINT_H_
#define SecondInnerPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* SecondInnerPlanCONSTRAINT_H_ */
