#ifndef ThirdInnerPlanCONSTRAINT_H_
#define ThirdInnerPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* ThirdInnerPlanCONSTRAINT_H_ */
