#include "Plans/HouseKeepingDomain/CarryBook1462889426092.h"
using namespace alica;
/*PROTECTED REGION ID(eph1462889426092) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:CarryBook

    //Check of PreCondition - (Name): NewPreCondition, (ConditionString): agent(A),  in(A,p1462889426092, T, S),  carries(A, b), book(b) , (Comment) :  

    /*
     * Available Vars:
     */
    bool PreCondition1462889683880::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1462889683880) ENABLED START*/
        //--> "PreCondition:1462889683880  not implemented";
        return true;
        /*PROTECTED REGION END*/
    }

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1462889438751

     */
    shared_ptr<UtilityFunction> UtilityFunction1462889426092::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1462889426092) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: NewState in Plan: CarryBook

}
