#include "Plans/HouseKeepingDomain/CarryBookMaster1462889118325.h"
using namespace alica;
/*PROTECTED REGION ID(eph1462889118325) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:CarryBookMaster

    /* generated comment
     
     Task: Attack  -> EntryPoint-ID: 1462889118327

     Task: Defend  -> EntryPoint-ID: 1462889160670

     */
    shared_ptr<UtilityFunction> UtilityFunction1462889118325::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1462889118325) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: CarryBookState1 in Plan: CarryBookMaster

//State: CarryBookState2 in Plan: CarryBookMaster

}
