#ifndef CarryBook_H_
#define CarryBook_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
#include "engine/UtilityFunction.h"
/*PROTECTED REGION ID(incl1462889426092) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1462889426092) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1462889426092 : public BasicUtilityFunction
{
    shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

class PreCondition1463404630976 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};

class TransitionCondition1463404654846 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};

} // namespace alicaAutogenerated

#endif
