#include "Plans/constraints/BrokenCardPlan1462879159773Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1462879159773) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:BrokenCardPlan

/*
 * Tasks:
 * - EP:1462879191637 : DefaultTask (1225112227903)
 *
 * States:
 * - BrokenPlanState (1462879191636)
 *
 * Vars:
 */

// State: BrokenPlanState

// State: BrokenPlanState

} // namespace alicaAutogenerated
