#include "Plans/constraints/CorrectCardPlan1462879199379Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1462879199379) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:CorrectCardPlan

/*
 * Tasks:
 * - EP:1462879220967 : DefaultTask (1225112227903)
 *
 * States:
 * - CorrectPlanState (1462879220966)
 *
 * Vars:
 */

// State: CorrectPlanState

// State: CorrectPlanState

} // namespace alicaAutogenerated
