#include "Plans/constraints/CyclePlanC1453033651069Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1453033651069) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:CyclePlanC

/*		
 * Tasks: 
 * - EP:1453033651071 : DefaultTask (1225112227903)
 *
 * States:
 * - NewState (1453033651070)
 *
 * Vars:
 */

// State: NewState

// State: NewState

}
