#include "Plans/constraints/CyclePlanA1453033636578Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1453033636578) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:CyclePlanA

/*		
 * Tasks: 
 * - EP:1453033636581 : DefaultTask (1225112227903)
 *
 * States:
 * - NewState (1453033636580)
 *
 * Vars:
 */

// State: NewState

// State: NewState

}
