#include "Plans/constraints/CyclePlanB1453033643893Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1453033643893) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:CyclePlanB

/*		
 * Tasks: 
 * - EP:1453033643895 : DefaultTask (1225112227903)
 *
 * States:
 * - NewState (1453033643894)
 *
 * Vars:
 */

// State: NewState

// State: NewState

}
