#include "Plans/constraints/EmptyPlan1455034580394Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1455034580394) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:EmptyPlan

/*		
 * Tasks: 
 *
 * States:
 *
 * Vars:
 */

}
