#include "Plans/constraints/HierarchicalInconsistentCardinalities1453033407259Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1453033407259) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:HierarchicalInconsistentCardinalities

/*
 * Tasks:
 * - EP:1453033407261 : DefaultTask (1225112227903)
 *
 * States:
 * - Max2AgentState (1453033407260)
 *
 * Vars:
 */

// State: Max2AgentState

// State: Max2AgentState

} // namespace alicaAutogenerated
