#include "Plans/constraints/InconsistentCardinalities1462886292442Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1462886292442) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:InconsistentCardinalities

/*		
 * Tasks: 
 * - EP:1462886292444 : Attack (1222613952469)
 * - EP:1462886310757 : AttackSupport (1225115536468)
 *
 * States:
 * - NewState (1462886292443)
 * - NewState (1462886315314)
 *
 * Vars:
 */

// State: NewState

// State: NewState

// State: NewState

// State: NewState

}
