#include "Plans/constraints/InconsistenCardinalities1462879046488Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1462879046488) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:InconsistenCardinalities

/*		
 * Tasks: 
 * - EP:1462879046490 : DefaultTask (1225112227903)
 *
 * States:
 * - PlanState (1462879046489)
 *
 * Vars:
 */

// State: PlanState

// State: PlanState

}
