#include "Plans/constraints/IndirectReusePlanInPlantype1462793790517Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1462793790517) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:IndirectReusePlanInPlantype

/*		
 * Tasks: 
 * - EP:1462793790519 : DefaultTask (1225112227903)
 *
 * States:
 * - PlantypeState (1462793790518)
 *
 * Vars:
 */

// State: PlantypeState

// State: PlantypeState

}
