#include "Plans/constraints/LocalInconsistentCardinalities1453033347284Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1453033347284) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:LocalInconsistentCardinalities

/*
 * Tasks:
 * - EP:1453033347286 : DefaultTask (1225112227903)
 *
 * States:
 * - NewState (1453033347285)
 *
 * Vars:
 */

// State: NewState

// State: NewState

} // namespace alicaAutogenerated
