#include "Plans/constraints/LowerPlanInPlantype1462793912377Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1462793912377) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:LowerPlanInPlantype

/*		
 * Tasks: 
 * - EP:1462793923281 : DefaultTask (1225112227903)
 *
 * States:
 * - LowerState (1462793923280)
 *
 * Vars:
 */

// State: LowerState

// State: LowerState

}
