#include "Plans/constraints/MasterPlan1441701747919Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1441701747919) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:MasterPlan

/*
 * Tasks:
 * - EP:1441701747921 : DefaultTask (1225112227903)
 *
 * States:
 * - RootState (1441701747920)
 * - SecondRootState (1441701781326)
 *
 * Vars:
 */

// State: RootState

// State: RootState

// State: SecondRootState

// State: SecondRootState

} // namespace alicaAutogenerated
