#include "Plans/constraints/Min3AgentPlan1453033506291Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1453033506291) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:Min3AgentPlan

/*		
 * Tasks: 
 * - EP:1453033506293 : DefaultTask (1225112227903)
 *
 * States:
 * - Min3AgentState (1453033506292)
 *
 * Vars:
 */

// State: Min3AgentState

// State: Min3AgentState

}
