#include "Plans/constraints/Min3AgentPlan1453033506291Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1453033506291) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:Min3AgentPlan

/*
 * Tasks:
 * - EP:1453033506293 : Attack (1222613952469)
 * - EP:1456483257411 : Defend (1225115406909)
 *
 * States:
 * - Min2AgentState (1453033506292)
 * - Min1AgentState (1456483282661)
 *
 * Vars:
 */

// State: Min2AgentState

// State: Min2AgentState

// State: Min1AgentState

// State: Min1AgentState

} // namespace alicaAutogenerated
