#include "Plans/constraints/NonLocalInRelation1456730912737Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1456730912737) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:NonLocalInRelation

/*
 * Tasks:
 * - EP:1456730912739 : Attack (1222613952469)
 * - EP:1456731546744 : Defend (1225115406909)
 *
 * States:
 * - NonLocalInState (1456730912738)
 * - ReferencedPlanState (1456731550573)
 *
 * Vars:
 */

// State: NonLocalInState

// State: NonLocalInState

// State: ReferencedPlanState

// State: ReferencedPlanState

} // namespace alicaAutogenerated
