#include "Plans/constraints/ReferencedPlan1456731591075Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1456731591075) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:ReferencedPlan

/*		
 * Tasks: 
 * - EP:1456731605617 : DefaultTask (1225112227903)
 *
 * States:
 * - StateInReferencedPlan (1456731605616)
 *
 * Vars:
 */

// State: StateInReferencedPlan

// State: StateInReferencedPlan

}
