#include "Plans/constraints/ReusePlanWithoutCycle1455093185652Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1455093185652) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:ReusePlanWithoutCycle

/*
 * Tasks:
 * - EP:1455093185654 : Attack (1222613952469)
 * - EP:1455093221781 : Defend (1225115406909)
 *
 * States:
 * - 1stTime (1455093185653)
 * - 2ndTime (1455093214694)
 *
 * Vars:
 */

// State: 1stTime

// State: 1stTime

// State: 2ndTime

// State: 2ndTime

} // namespace alicaAutogenerated
