#include "Plans/constraints/ReusePlanFromPlantypeWithoutCycle1464355916688Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1464355916688) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:ReusePlanFromPlantypeWithoutCycle

/*
 * Tasks:
 * - EP:1464355916690 : DefaultTask (1225112227903)
 *
 * States:
 * - PlantypeState (1464355916689)
 *
 * Vars:
 */

// State: PlantypeState

// State: PlantypeState

} // namespace alicaAutogenerated
