#include "Plans/constraints/SingleUnconnectedState1452783421979Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1452783421979) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:SingleUnconnectedState

/*		
 * Tasks: 
 * - EP:1452783421981 : DefaultTask (1225112227903)
 *
 * States:
 * - Unconnected State (1452783421980)
 * - AlibiState (1453391861179)
 *
 * Vars:
 */

// State: Unconnected State

// State: Unconnected State

// State: AlibiState

// State: AlibiState

}
