#include "Plans/constraints/TaskTwicePlan1453033761283Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1453033761283) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:TaskTwicePlan

/*
 * Tasks:
 * - EP:1453033761285 : DefaultTask (1225112227903)
 * - EP:1453033782170 : DefaultTask (1225112227903)
 *
 * States:
 * - Task1State (1453033761284)
 * - Task2State (1453033775911)
 *
 * Vars:
 */

// State: Task1State

// State: Task1State

// State: Task2State

// State: Task2State

} // namespace alicaAutogenerated
