#include "Plans/constraints/UnconnectedStateMachine1452783558494Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1452783558494) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:UnconnectedStateMachine

/*		
 * Tasks: 
 * - EP:1452783558496 : DefaultTask (1225112227903)
 *
 * States:
 * - State1 (1452783558495)
 * - State2 (1452783576711)
 * - State3 (1452783579086)
 * - State4 (1452783583119)
 * - AlibiState (1453392283151)
 *
 * Vars:
 */

// State: State1

// State: State1

// State: State2

// State: State2

// State: State3

// State: State3

// State: State4

// State: State4

// State: AlibiState

// State: AlibiState

}
