#include "Plans/constraints/UnconnectedState1441701808444Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1441701808444) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:UnconnectedState

/*
 * Tasks:
 * - EP:1441701830557 : DefaultTask (1225112227903)
 *
 * States:
 * - connected (1441701830556)
 * - unconnected (1441701840600)
 *
 * Vars:
 */

// State: connected

// State: connected

// State: unconnected

// State: unconnected

} // namespace alicaAutogenerated
