#include "Plans/constraints/UnconnectedSynchronisations1455035766972Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1455035766972) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:UnconnectedSynchronisations

/*		
 * Tasks: 
 * - EP:1455035766974 : Attack (1222613952469)
 * - EP:1455035846736 : Defend (1225115406909)
 *
 * States:
 * - StateABefore (1455035766973)
 * - StateAAfter (1455035790843)
 * - StateDBefore (1455035838383)
 * - StateDAfter (1455035874846)
 *
 * Vars:
 */

// State: StateABefore

// State: StateABefore

// State: StateAAfter

// State: StateAAfter

// State: StateDBefore

// State: StateDBefore

// State: StateDAfter

// State: StateDAfter

}
