#include "Plans/constraints/UpperPlanInPlantype1462793904808Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1462793904808) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:UpperPlanInPlantype

/*		
 * Tasks: 
 * - EP:1462793904810 : DefaultTask (1225112227903)
 *
 * States:
 * - UpperState (1462793904809)
 *
 * Vars:
 */

// State: UpperState

// State: UpperState

}
